services:
  api:
    ports:
      # Exposes application port.
    - "8000:8000"
    build:
      context: .
    volumes:
      # Adds current directory as volume.
    - .:/app/src/
    environment:
      # Enables autoreload.
      SAVER_BACKEND_RELOAD: "True"

  taskiq-worker:
    volumes:
      # Adds current directory as volume.
      - .:/app/src/
    command:
      - scripts/start_taskiq_worker.sh
      - --with-reload

  db:
    ports:
      - "5432:5432"

  redis:
    ports:
      - "6379:6379"
