"""Add history table.

Revision ID: 5b6bf21e7dc6
Revises: 0875214f29a6
Create Date: 2025-11-08 13:26:13.986189

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "5b6bf21e7dc6"
down_revision = "0875214f29a6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Run the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "history",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("cache_id", sa.UUID(), nullable=True),
        sa.Column("source", sa.String(length=50), nullable=False),
        sa.Column("url", sa.String(length=1024), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["cache_id"], ["cache.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_index(op.f("ix_video_cache_source_id"), table_name="cache")
    op.create_index("ix_cache_source_id", "cache", ["source_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Undo the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_cache_source_id", table_name="cache")
    op.create_index(
        op.f("ix_video_cache_source_id"),
        "cache",
        ["source_id"],
        unique=False,
    )
    op.drop_table("history")
    # ### end Alembic commands ###
