"""Add detailed fields to VideoCacheModel.

Revision ID: 19b445ddc1a7
Revises: ca43dd3fe1ff
Create Date: 2025-10-23 14:06:30.782138

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "19b445ddc1a7"
down_revision = "ca43dd3fe1ff"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Run the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "video_cache",
        sa.Column(
            "quality",
            sa.String(length=50),
            server_default=sa.text("'best'"),
            nullable=False,
        ),
    )
    op.drop_constraint(op.f("uq_source_source_id"), "video_cache", type_="unique")
    op.create_unique_constraint(
        "uq_source_id_quality",
        "video_cache",
        ["source", "source_id", "quality"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Undo the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_source_id_quality", "video_cache", type_="unique")
    op.create_unique_constraint(
        op.f("uq_source_source_id"),
        "video_cache",
        ["source", "source_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("video_cache", "quality")
    # ### end Alembic commands ###
