name: tests

on: push

permissions:
  contents: read

jobs:
  lint:
    strategy:
      matrix:
        include:
          - name: Ruff format
            cmd: ruff format --diff saver_backend tests
          - name: Ruff check
            cmd: ruff check saver_backend tests
          - name: Mypy
            cmd: mypy saver_backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v8.1.0
        with:
          version: "0.11.11"
          # renovate: datasource=github-releases depName=python packageName=python/cpython versioning=pep440
          python-version: "3.14"
          enable-cache: "auto"

      - name: Install deps
        run: uv sync --locked --all-groups

      - name: ${{ matrix.name }}
        run: uv run ${{ matrix.cmd }}

  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Create .env
        run: touch .env

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build api image (cached)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          target: dev
          tags: saver_backend:ci
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Run tests
        env:
          SAVER_BACKEND_VERSION: ci
        run: docker compose run --rm api pytest -vv
