name: Tolgee push new keys

on:
  push:
    branches:
      - main
      - dev
  workflow_dispatch:

jobs:
  tolgee-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install Tolgee CLI
        run: npm install -g @tolgee/cli

      - name: Create GitHub App token
        id: app-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Push new translation keys to Tolgee
        working-directory: locales
        env:
          TOLGEE_API_URL: ${{ secrets.TOLGEE_API_URL }}
          TOLGEE_API_KEY: ${{ secrets.TOLGEE_API_KEY }}
          TOLGEE_PROJECT_ID: ${{ secrets.TOLGEE_PROJECT_ID }}
        run: |
          RAW_MSG="${{ github.event.head_commit.message }}"
          DESC_PART=$(echo "$RAW_MSG" | awk -F':' '{if (NF>1) {print $2} else {print $1}}')
          DESC_PART=$(echo "$DESC_PART" | xargs)
          CLEAN_MSG=$(echo "$DESC_PART" | tr -dc '[:alnum:][:space:]_-' | tr ' ' '_' | cut -c1-40)

          echo "🔹 Pushing translations with tag: $CLEAN_MSG"
          tolgee push \
            --api-url $TOLGEE_API_URL \
            --api-key $TOLGEE_API_KEY \
            --project-id $TOLGEE_PROJECT_ID \
            --verbose \
            --force-mode KEEP \
            --files-template "{languageTag}/LC_MESSAGES/messages.po" \
            --format PO_ICU \
            --tag-new-keys "$CLEAN_MSG"
